name: Build Unity Job
on:
  push:
    branches:    
      - main

jobs:
  build:
    name: Build my project
    runs-on: ubuntu-latest
    steps:
      # Checkout (without LFS)
      - name: Checkout repository
        uses: actions/checkout@v2

      # Git LFS
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-        
          
      - name: "Freeing up disk space"
        run: |
          echo "############################################"
          echo "#    Freeing up disk space on CI system    #"
          echo "############################################"
          echo -n "Disk space before:"
          df -h / --output=avail | tail -1
          # https://github.com/apache/flink/blob/master/tools/azure-pipelines/free_disk_space.sh
          rm -rf /usr/share/dotnet/
          # https://github.com/actions/virtual-environments/issues/709#issuecomment-612569242
          rm -rf "/usr/local/share/boost"
          rm -rf "$AGENT_TOOLSDIRECTORY"
          echo -n "Disk space after:"
          df -h / --output=avail | tail -1
          
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: LF08_Unity
          targetPlatform: StandaloneWindows
          allowDirtyBuild: true

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: LF08Project
          path: build
          
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/LF08Project"
          token: ${{ secrets.GITHUB_TOKEN }}
